CREATE TABLE IF NOT EXISTS complaint_sequence (id INT PRIMARY KEY, next_number BIGINT NOT NULL) ENGINE=InnoDB;
INSERT IGNORE INTO complaint_sequence(id,next_number) VALUES(1,1);
CREATE TABLE IF NOT EXISTS complaints (id BIGINT AUTO_INCREMENT PRIMARY KEY, reference VARCHAR(40) UNIQUE NOT NULL, idempotency_key CHAR(64) UNIQUE NOT NULL, body_hash CHAR(64) NOT NULL, data LONGTEXT NOT NULL, created_at VARCHAR(30) NOT NULL, version INT NOT NULL DEFAULT 0) ENGINE=InnoDB;
